basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Show a Hello message
swagger: "2.0"
